source 'https://rubygems.org'
ruby '2.3.1'
gem 'rails', '~> 5.0.0'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'foundation-rails', '5.5.2.1'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'ancestry'
gem 'hamlit'

gem 'devise'
gem 'jquery-turbolinks'
gem 'foundation-icons-sass-rails'
gem 'rails_12factor'
gem 'redcarpet'
gem 'puma'
gem 'imgur_url'
gem 'httparty'
gem 'newrelic_rpm'
gem 'web-console', '~> 2.0', group: :development
gem 'redis'
gem 'redis-rails', '~> 5.0.0.pre'
group :development, :test do
  gem 'dotenv-rails'
  gem 'rack-mini-profiler', require: false
  gem 'flamegraph'
  gem 'stackprof'
  gem 'letter_opener'
  gem 'spring'
  gem 'annotate'
  gem 'faker'
  gem 'bullet'
  gem 'brakeman'
  gem 'pry'
  gem 'pry-rails'
  gem 'simplecov'
  gem 'rails-controller-testing'
end
