# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e77255abf0599ee66f4292425c19d5962ab49ae094b50575463d222f338597d7ddeb3e38124915fc8633fb5faa6f4136c69e8048af7ba72dfb7282278d3c75d2

test:
  secret_key_base: 3caa0c9a9b3344fdb02480b0699b94e804494a6af796cea7b0aa64c7d5249b797f44e41db28a54b2b4acc004f14fd19ce50abe50480b1227f5d5419055b06233

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
